import { createHash } from 'node:crypto';
import { NextResponse } from 'next/server';
import init, { solve_flop } from '@jayj1990/gto-today-solver-wasm';
import { SOLVER_WASM_BYTES, SOLVER_WASM_VERSION } from '@/lib/solver-wasm-bytes';
import { cacheGet, cacheSet, CACHE_BACKEND } from '@/lib/solve-cache';

export const runtime = 'nodejs';
export const maxDuration = 300; // Vercel Fluid Compute — up to 300s

// Solve cache: Upstash Redis when env vars are set (shared across all
// Fluid Compute instances and cold starts), otherwise an in-memory map
// scoped to the current warm instance. Both live behind cacheGet/cacheSet
// so the rest of this route doesn't care.

function fingerprint(body: SolveRequest): string {
  // Canonical string so the hash is order-independent for ranges
  // (users may re-enter the same ranges in different comma orders).
  // Accuracy + maxIter are in the key: a higher-accuracy re-solve
  // won't be served from a coarser cached result.
  const canon = [
    body.board.slice().sort().join(''),
    canonRange(body.oopRange),
    canonRange(body.ipRange),
    body.pot.toFixed(2),
    body.effStack.toFixed(2),
    body.scenario,
    (body.accuracy ?? 0.5).toFixed(2),
    String(body.maxIter ?? 150),
    SOLVER_WASM_VERSION,
  ].join('|');
  return createHash('sha256').update(canon).digest('hex').slice(0, 16);
}

function canonRange(r: string): string {
  return r
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .sort()
    .join(',');
}

/**
 * Live postflop solver endpoint. The WASM binary ships as a base64
 * string inside SOLVER_WASM_BYTES (generated by scripts/bundle-wasm
 * from the @jayj1990/gto-today-solver-wasm package). The web-target
 * wrapper's `init()` takes those bytes as an ArrayBuffer, so we never
 * touch the filesystem — sidesteps Vercel's Function packager
 * filtering .wasm files out of .next/server/chunks/.
 *
 * Mock fallback stays as a last-resort net; if init() or solve_flop()
 * throws we log it and return a plausible texture-based strategy so
 * the UI never hard-fails.
 */

// Lazy init — the module-load eager init tried to save 100-500ms on
// cold starts but if init() threw (e.g. wasm-bindgen rejecting the
// byte shape) the whole Function failed to load and Vercel returned
// raw HTML error pages the client couldn't parse as JSON. Defer to
// the first POST so failures become catchable JSON errors.
let wasmReady: Promise<void> | null = null;
function ensureWasmReady(): Promise<void> {
  if (wasmReady === null) {
    wasmReady = (async () => {
      await init(SOLVER_WASM_BYTES);
    })();
  }
  return wasmReady;
}

export interface SolveRequest {
  /** Three flop cards, e.g. ['As','Kh','7d']. */
  board: [string, string, string];
  /** Pio-style range strings. */
  oopRange: string;
  ipRange: string;
  /** Pot in BB at flop, effective stack in BB. */
  pot: number;
  effStack: number;
  /** 'cash' (no ante) or 'mtt' (ante baked into pot). */
  scenario: 'cash' | 'mtt';
  /** Target exploitability in % (lower = more accurate, slower). Default 0.5. */
  accuracy?: number;
  /** Hard iteration cap so runaway solves can't exceed the Function timeout. Default 150. */
  maxIter?: number;
}

export interface SolveResponse {
  /** Action labels in order — matches PostflopAction enum. */
  actions: string[];
  /** Per-169 hand mix across actions. Sums to ~1 per combo. */
  mix: Record<string, number[]>;
  exploitability: number;
  iterations: number;
  elapsedMs: number;
  note?: string;
}

export async function POST(req: Request): Promise<NextResponse<SolveResponse | { error: string }>> {
  // Wrap the whole handler so any unexpected throw (WASM init, cache
  // adapter, JSON serialization, etc.) becomes a proper JSON error
  // response instead of a Vercel HTML crash page the client can't
  // parse with response.json().
  try {
    return await handleSolve(req);
  } catch (e) {
    const msg = e instanceof Error ? `${e.name}: ${e.message}` : String(e);
    console.error('[live-solve] unhandled error:', msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

async function handleSolve(
  req: Request,
): Promise<NextResponse<SolveResponse | { error: string }>> {
  let body: SolveRequest;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Bad JSON' }, { status: 400 });
  }

  if (!body.board || body.board.length !== 3) {
    return NextResponse.json({ error: 'board must be 3 cards' }, { status: 400 });
  }

  const start = Date.now();

  // Cache check — avoid re-running a 30-200s solve for the same spot.
  const fp = fingerprint(body);
  const cached = await cacheGet<SolveResponse>(fp);
  if (cached) {
    return NextResponse.json({
      ...cached,
      elapsedMs: Date.now() - start,
      note: `cache hit · ${CACHE_BACKEND} · fp=${fp}`,
    });
  }

  let wasmError: string | null = null;
  try {
    await ensureWasmReady();
    const out = solve_flop({
      board: body.board,
      oop_range: body.oopRange,
      ip_range: body.ipRange,
      pot: body.pot,
      eff_stack: body.effStack,
      accuracy: body.accuracy ?? 0.5,
      max_iter: body.maxIter ?? 150,
    }) as {
      actions: string[];
      mix: Record<string, number[]>;
      exploitability: number;
      iterations: number;
    };
    const response: SolveResponse = {
      actions: out.actions,
      mix: out.mix,
      exploitability: out.exploitability,
      iterations: out.iterations,
      elapsedMs: Date.now() - start,
    };
    // Fire-and-forget cache write; we don't want a slow Redis to
    // delay the response the user is already waiting for.
    void cacheSet(fp, response);
    return NextResponse.json(response);
  } catch (e) {
    wasmError = e instanceof Error ? e.message : String(e);
    // Log the full spot so we can correlate failing inputs against
    // the Vercel Function logs — panic messages from wasm32 don't
    // survive to JS, so the spot itself is the best clue we have.
    console.error('[live-solve] WASM failed:', {
      err: wasmError,
      board: body.board,
      oopCombos: body.oopRange.split(',').length,
      ipCombos: body.ipRange.split(',').length,
      pot: body.pot,
      effStack: body.effStack,
      scenario: body.scenario,
      fp,
    });
  }

  const result = mockSolve(body);
  result.elapsedMs = Date.now() - start;
  result.note = `Mock — WASM ${SOLVER_WASM_VERSION} error: ${wasmError ?? 'unknown'}`;
  return NextResponse.json(result);
}

/** Placeholder postflop strategy generator driven by board texture.
 *  Values are plausible (A-high → cbet-heavy, paired → check-heavy,
 *  monotone → small-bet only) but NOT GTO-accurate. Swap with real
 *  WASM call once solver-wasm package is ready. */
function mockSolve(req: SolveRequest): SolveResponse {
  const { board } = req;
  const ranks = board.map((c) => c[0]!);
  const suits = board.map((c) => c[1]!);
  const monotone = new Set(suits).size === 1;
  const paired = new Set(ranks).size < 3;
  const hasAce = ranks.includes('A');

  // Match solver-wasm 0.5+ action set: check + bet50 only.
  const actions = ['check', 'bet50'];

  // Baseline check/bet split per board texture.
  let base: [number, number];
  if (monotone) base = [0.8, 0.2];
  else if (paired) base = [0.85, 0.15];
  else if (hasAce) base = [0.4, 0.6]; // cbet-heavy on A-high
  else base = [0.6, 0.4];

  const mix: Record<string, number[]> = {};
  const ranksOrder = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];
  for (let i = 0; i < 13; i++) {
    for (let j = 0; j < 13; j++) {
      const hi = ranksOrder[i]!;
      const lo = ranksOrder[j]!;
      let combo: string;
      if (i === j) combo = hi + lo;
      else if (i < j) combo = hi + lo + 's';
      else combo = lo + hi + 'o';

      const strength = handStrength(combo, hasAce);
      const bias = (strength - 0.5) * 0.3; // ±0.15 shift toward bet for strong
      const c = clamp01(base[0] - bias);
      const b = clamp01(base[1] + bias);
      const total = c + b;
      mix[combo] = [c / total, b / total];
    }
  }

  return {
    actions,
    mix,
    exploitability: 0.5, // mock — real solver would converge here
    iterations: 100,
    elapsedMs: 0,
    note: 'Mock strategy — WASM solver integration pending',
  };
}

function clamp01(x: number): number {
  return Math.max(0, Math.min(1, x));
}

/** Very rough hand-strength proxy for mock mix — scale 0..1. */
function handStrength(combo: string, hasAceBoard: boolean): number {
  if (combo === 'AA' || combo === 'KK') return 0.95;
  if (combo === 'QQ' || combo === 'JJ') return 0.85;
  if (combo === 'TT' || combo === '99') return 0.75;
  if (combo.startsWith('A')) return hasAceBoard ? 0.8 : 0.55;
  if (combo.startsWith('K')) return 0.6;
  if (combo.endsWith('s') && combo[0] === combo[1]) return 0.7; // pair
  if (combo.endsWith('s')) return 0.45; // suited
  if (combo.endsWith('o')) return 0.3; // offsuit
  return 0.4;
}
